configuration:
    dependencies:
    - "mvn://org.python:jython-standalone:2.7.2"
    arguments: 
      myVar: "world"

flows:
  default:
  - log: "Hello Concord User from a modified workflow"

  githubTriggered:
  - log: "Something was pushed"

  cronTask:
    - log: "Just printing something with a minute base"

  httpFeature:
    - task: http
      in:
        url: "https://jsonplaceholder.typicode.com/todos/${todoId}"
        response: json
        out: myTodo

    - if: "${myTodo.content.completed}"
      then:
        - log: "All done!"
      else:
        - log: "You got a todo item: ${myTodo.content.title}"
  
  testingVars:
    - script: python
      body: |
        x = 2 * 3;
        execution.setVariable("result", x)

    - log: ${result}
  
  dockertask:
    - task: docker
      in:
        image: library/alpine
        cmd: echo '${greeting}'
      out: dockerResult


triggers:
  - cron: 
      spec: "* * * * *"
      entryPoint: cronTask

  - github:
      entryPoint: "githubTriggered"
      conditions:
        type: "push"
    